version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
      - 8000:8000
      - 9000:9000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  portainer_data:

# docker-compose up -d
#
# or without compose
# docker run -d -p 8000:8000 -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce